export { createHttpResponsePage }
export { createHttpResponsePageJson }
export { createHttpResponseErrorFallback }
export { createHttpResponseErrorFallback_noGlobalContext }
export { createHttpResponseErrorFallbackJson }
export { createHttpResponseRedirect }
export { createHttpResponse404 }
export { createHttpResponseBaseIsMissing }
export { createHttpResponseFromUniversalMiddleware }
export { createHttpResponseArtifact }
export { getStatusCodePage }
export type { HttpResponse }

import type { GetPageAssets } from './getPageAssets.js'
import { escapeHtml } from '../../../utils/escapeHtml.js'
import { assert, assertUsage, assertWarning } from '../../../utils/assert.js'
import type { HtmlRender } from './html/renderHtml.js'
import { getErrorPageId, isErrorPage } from '../../../shared-server-client/error-page.js'
import type { RenderHook } from './execHookOnRenderHtml.js'
import type { RedirectStatusCode, AbortStatusCode, UrlRedirect } from '../../../shared-server-client/route/abort.js'
import {
  getHttpResponseBody,
  getHttpResponseBodyStreamHandlers,
  HttpResponseBody,
  type ResponseBody,
} from './getHttpResponseBody.js'
import { getEarlyHints, type EarlyHint } from './getEarlyHints.js'
import { assertNoInfiniteHttpRedirect } from './createHttpResponse/assertNoInfiniteHttpRedirect.js'
import type { PageContextBegin } from '../renderPageServer.js'
import type { GlobalContextServerInternal } from '../globalContext.js'
import { headersToEntriesPreservingSetCookie, resolveHeadersResponseFinal } from './headersResponse.js'
import { stringify } from '@brillout/json-serializer/stringify'
import { isStream, processStream } from './html/stream.js'
import type { ResponseArtifact, ResponseIntent } from '../../../types/RenderTarget.js'
import '../../assertEnvServer.js'

type HttpResponse = {
  statusCode: number
  headers: [string, string][]
  earlyHints: EarlyHint[]
  // We don't use @deprecated to avoid TypeScript to remove the JSDoc
  /** **Deprecated**: use `headers` instead, see https://vike.dev/migration/0.4.134 */
  contentType: string | undefined
} & HttpResponseBody

const contentTypeJson = 'application/json'
const contentTypeHtml = 'text/html;charset=utf-8'
const htmlFallbackLog = 'This HTML was generated by Vike.'

type StatusCode = 200 | 404 | 500 | RedirectStatusCode | AbortStatusCode
type ContentType = 'application/json' | 'text/html;charset=utf-8'
type ResponseHeaders = HttpResponse['headers']

async function createHttpResponsePage(
  htmlRender: HtmlRender,
  renderHook: null | RenderHook,
  pageContext: {
    pageId: null | string
    is404: null | boolean
    errorWhileRendering: null | Error
    __getPageAssets: GetPageAssets
    _globalContext: GlobalContextServerInternal
    abortStatusCode?: AbortStatusCode
    headersResponse?: Headers
  },
): Promise<HttpResponse> {
  const statusCode = getStatusCodePage(pageContext)

  const earlyHints = getEarlyHints(await pageContext.__getPageAssets())
  const headers = resolveHeadersResponseFinal(pageContext, statusCode)
  return createHttpResponse(statusCode, contentTypeHtml, headers, htmlRender, earlyHints, renderHook)
}

function getStatusCodePage(pageContext: {
  pageId: null | string
  is404: null | boolean
  errorWhileRendering: null | Error
  _globalContext: GlobalContextServerInternal
  abortStatusCode?: AbortStatusCode
}): StatusCode {
  let statusCode: StatusCode | undefined = pageContext.abortStatusCode
  if (!statusCode) {
    const isError = !pageContext.pageId || isErrorPage(pageContext.pageId, pageContext._globalContext._pageConfigs)
    if (pageContext.errorWhileRendering) {
      assert(isError)
    }
    if (!isError) {
      assert(pageContext.is404 === null)
      statusCode = 200
    } else {
      assert(pageContext.is404 === true || pageContext.is404 === false)
      statusCode = pageContext.is404 ? 404 : 500
    }
  }
  return statusCode
}

function createHttpResponse404(errMsg404: string): HttpResponse {
  const httpResponse = createHttpResponse(404, contentTypeHtml, [], getHtmlFallback(`<p>${errMsg404}.</p>`))
  return httpResponse
}

function createHttpResponseBaseIsMissing(urlOriginal: string, baseServer: string): HttpResponse {
  const httpResponse = createHttpResponse(
    // We use the error code `500` to signal a failing state because this HTTP response should never be used, see https://vike.dev/base-url#setup
    // In other words: this HTTP response is expected to be generated but isn't expected to be actually used.
    500,
    contentTypeHtml,
    [],
    `
<h1>Error: Base URL is missing</h1>
<p>
  <a href="https://vike.dev/renderPage"><code>renderPage(pageContextInit)</code></a> called with <code>pageContextInit.urlOriginal===${JSON.stringify(urlOriginal)}</code> which doesn't start with the Base URL <code>${baseServer}</code>.
</p>
<p>
  See <a href="https://vike.dev/base-url#setup">vike.dev/base-url#setup</a> for how to properly setup your server while using a Base URL.
</p>
<style>
  code {
    font-family: monospace;
    background-color: #eaeaea;
    padding: 3px 5px;
    border-radius: 4px;
  }
</style>
`,
  )
  return httpResponse
}
function createHttpResponseErrorFallback(pageContext: {
  _globalContext: GlobalContextServerInternal
}) {
  const reason = (() => {
    const errorPageId = getErrorPageId(
      pageContext._globalContext._pageFilesAll,
      pageContext._globalContext._pageConfigs,
    )
    if (errorPageId) {
      return "the error page (https://vike.dev/error-page) couldn't be rendered (for example if an error occurred while rendering the error page)" as const
    } else {
      return 'no error page (https://vike.dev/error-page) is defined, make sure to create one' as const
    }
  })()
  return createHttpResponseError_(reason)
}
function createHttpResponseErrorFallback_noGlobalContext() {
  return createHttpResponseError_('no error page (https://vike.dev/error-page) could be rendered')
}
function createHttpResponseError_(reason: string): HttpResponse {
  const httpResponse = createHttpResponse(
    500,
    contentTypeHtml,
    [],
    getHtmlFallback('<p>An error occurred.</p>', `${htmlFallbackLog} Vike returned this HTML because ${reason}.`),
  )
  return httpResponse
}
function createHttpResponseErrorFallbackJson() {
  const httpResponse = createHttpResponse(500, contentTypeJson, [], stringify({ serverSideError: true }))
  return httpResponse
}

async function createHttpResponsePageJson(pageContextSerialized: string) {
  const httpResponse = createHttpResponse(200, contentTypeJson, [], pageContextSerialized, [], null)
  return httpResponse
}

function createHttpResponseRedirect({ url, statusCode }: UrlRedirect, pageContextInit: PageContextBegin): HttpResponse {
  assertNoInfiniteHttpRedirect(url, pageContextInit)
  assert(url)
  assert(statusCode)
  assert(300 <= statusCode && statusCode <= 399)
  const headers: ResponseHeaders = [['Location', url]]
  return createHttpResponse(
    statusCode,
    contentTypeHtml,
    headers,
    // For bots / programmatic crawlig: show what's going on.
    // For users: showing a blank page is probably better than a flickering text.
    getHtmlFallback(`<p style="display: none">Redirecting to ${escapeHtml(url)}</p>`),
  )
}

function createHttpResponseFromUniversalMiddleware(response: Response, earlyHints?: EarlyHint[]) {
  const body = response.body ?? getHtmlFallback('<p style="display: none">No HTTP response body.</p>')
  const httpResponse = createHttpResponseCommon(
    response.status,
    headersToEntriesPreservingSetCookie(response.headers),
    body,
    earlyHints,
  )
  return httpResponse
}

async function createHttpResponseArtifact(
  artifact: ResponseArtifact,
  responseIntent: ResponseIntent,
): Promise<HttpResponse> {
  assertResponseArtifact(artifact)

  let body: ResponseBody = artifact.body
  if (artifact.onErrorWhileStreaming && isStream(body)) {
    body = await processStream(body, {
      onErrorWhileStreaming: artifact.onErrorWhileStreaming,
      // Once encodeOutcome() returns, Vike has no representation-neutral way to replace emitted bytes.
      enableEagerStreaming: true,
    })
  }

  const headers = mergeArtifactHeaders(artifact, responseIntent.headers)
  return createHttpResponseCommon(artifact.statusCode, headers, body, [], null, 'artifact')
}

function getHtmlFallback(bodyHtml: string, logText: string = htmlFallbackLog): string {
  return `${bodyHtml}<script>console.log(${JSON.stringify(logText)})</script>`
}

function createHttpResponse(
  statusCode: StatusCode,
  contentType: ContentType,
  headers: ResponseHeaders,
  htmlRender: HtmlRender,
  earlyHints?: EarlyHint[],
  renderHook?: null | RenderHook,
): HttpResponse {
  headers.push(['Content-Type', contentType])

  assert(renderHook || typeof htmlRender === 'string')
  return createHttpResponseCommon(statusCode, headers, htmlRender, earlyHints, renderHook)
}

function createHttpResponseCommon(
  statusCode: number,
  headers: ResponseHeaders,
  responseBody: ResponseBody,
  earlyHints: EarlyHint[] = [],
  renderHook: null | RenderHook = null,
  bodyKind: 'html' | 'artifact' = 'html',
): HttpResponse {
  const contentType = headers.find(([k]) => k.toLowerCase() === 'content-type')?.[1]
  return {
    statusCode,
    headers,
    // TO-DO/next-major-release: remove
    get contentType() {
      assertWarning(
        false,
        'pageContext.httpResponse.contentType is deprecated and will be removed in the next major release. Use pageContext.httpResponse.headers instead, see https://vike.dev/migration/0.4.134',
        { onlyOnce: true },
      )
      return contentType
    },
    earlyHints,
    get body() {
      return getHttpResponseBody(responseBody, renderHook)
    },
    ...getHttpResponseBodyStreamHandlers(responseBody, renderHook, bodyKind),
  }
}

function assertResponseArtifact(artifact: ResponseArtifact): void {
  assertUsage(artifact && typeof artifact === 'object', 'renderTarget.encodeOutcome() should return an object')
  assertUsage(
    Number.isInteger(artifact.statusCode) && artifact.statusCode >= 100 && artifact.statusCode <= 599,
    'renderTarget.encodeOutcome() should return a statusCode between 100 and 599',
  )
  assertUsage(Array.isArray(artifact.headers), 'renderTarget.encodeOutcome() should return headers as an array')
  artifact.headers.forEach(assertHeader)
  assertUsage(
    !artifact.headers.some(([name]) => name.toLowerCase() === 'content-type'),
    'Content-Type is reserved to renderTarget.encodeOutcome().contentType: remove it from ResponseArtifact.headers',
  )
  if (artifact.contentType !== undefined) {
    assertUsage(
      typeof artifact.contentType === 'string' &&
        artifact.contentType.length > 0 &&
        !hasInvalidHeaderChars(artifact.contentType),
      'renderTarget.encodeOutcome().contentType should be a non-empty HTTP header value',
    )
  }
  assertUsage(
    typeof artifact.body === 'string' || artifact.body instanceof Uint8Array || isStream(artifact.body),
    'renderTarget.encodeOutcome().body should be a string, Uint8Array, Web ReadableStream, or Node.js Readable stream',
  )
  assertUsage(
    artifact.onErrorWhileStreaming === undefined || typeof artifact.onErrorWhileStreaming === 'function',
    'renderTarget.encodeOutcome().onErrorWhileStreaming should be a function',
  )
}

function mergeArtifactHeaders(
  artifact: ResponseArtifact,
  responseIntentHeaders: ResponseIntent['headers'],
): ResponseHeaders {
  const headers: ResponseHeaders = []
  const singleValueHeaders = new Set([
    'content-encoding',
    'content-length',
    'content-range',
    'location',
    'transfer-encoding',
  ])

  artifact.headers.forEach(([name, value]) => add(name, value))
  if (artifact.contentType) add('Content-Type', artifact.contentType)
  responseIntentHeaders.forEach(([name, value]) => {
    assertHeader([name, value])
    assertUsage(
      name.toLowerCase() !== 'content-type',
      'Content-Type is reserved to the render target: remove Content-Type from headersResponse',
    )
    add(name, value)
  })
  return headers

  function add(name: string, value: string) {
    const nameLower = name.toLowerCase()
    const existing = headers.filter(([existingName]) => existingName.toLowerCase() === nameLower)
    if (singleValueHeaders.has(nameLower) && existing.length > 0) {
      assertUsage(
        existing.every(([, existingValue]) => existingValue === value),
        `Conflicting ${name} response headers cannot be merged losslessly`,
      )
      return
    }
    headers.push([name, value])
  }
}

function assertHeader(header: readonly [string, string]): void {
  assertUsage(
    Array.isArray(header) &&
      header.length === 2 &&
      typeof header[0] === 'string' &&
      header[0].length > 0 &&
      typeof header[1] === 'string' &&
      !hasInvalidHeaderChars(header[0]) &&
      !hasInvalidHeaderChars(header[1]),
    'ResponseArtifact.headers should contain [name, value] string tuples without line breaks',
  )
}

function hasInvalidHeaderChars(value: string): boolean {
  return value.includes('\r') || value.includes('\n')
}
